#!/usr/bin/env python3
"""Monthly rollup of copy edit patterns. Run on the 1st of each month or manually."""

import sqlite3
import os
import sys
from datetime import datetime, timedelta
from collections import Counter

DB_PATH = os.path.join(os.path.dirname(__file__), "ktlyst-metrics.db")
MEMORY_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "memory")

def analyze_edits(days=30):
    if not os.path.exists(DB_PATH):
        print("ERROR: Database not found. Run db-init.py first.", file=sys.stderr)
        sys.exit(1)

    db = sqlite3.connect(DB_PATH)
    since = (datetime.now() - timedelta(days=days)).strftime("%Y-%m-%d")

    edits = db.execute(
        "SELECT original_text, edited_text, diff_summary, context, edit_date "
        "FROM copy_edits WHERE edit_date >= ? ORDER BY edit_date DESC",
        (since,)
    ).fetchall()

    if not edits:
        print(f"No edits found in the last {days} days.")
        db.close()
        return

    # Analyze patterns
    context_counts = Counter()
    summary_words = Counter()
    length_changes = []

    for orig, edited, summary, context, date in edits:
        context_counts[context] += 1
        if summary:
            for word in summary.lower().split():
                summary_words[word] += 1
        if orig and edited:
            orig_len = len(orig.split())
            edit_len = len(edited.split())
            pct = round((edit_len - orig_len) / orig_len * 100, 1) if orig_len > 0 else 0
            length_changes.append(pct)

    avg_length_change = round(sum(length_changes) / len(length_changes), 1) if length_changes else 0

    # Build report
    month = datetime.now().strftime("%Y-%m")
    report = f"""# Copy Learnings - {month}

## Summary
- Total edits analyzed: {len(edits)}
- Period: last {days} days (since {since})
- Average length change: {avg_length_change}% (negative = shorter)

## Edit frequency by context
"""
    for ctx, count in context_counts.most_common():
        report += f"- {ctx}: {count} edits\n"

    report += "\n## Common edit patterns\n"

    # Extract recurring diff summaries
    summaries = [e[2] for e in edits if e[2]]
    if summaries:
        # Simple frequency analysis of key phrases
        phrases = Counter()
        for s in summaries:
            for phrase in s.lower().split(","):
                phrase = phrase.strip()
                if len(phrase) > 5:
                    phrases[phrase] += 1
        for phrase, count in phrases.most_common(10):
            if count >= 2:
                report += f"- \"{phrase}\" (appeared {count} times)\n"

    report += f"""
## Recommendations for AI copy generation
Based on {len(edits)} founder edits:
"""
    if avg_length_change < -10:
        report += f"- Founder consistently shortens copy by ~{abs(avg_length_change)}%. Generate shorter drafts.\n"
    if avg_length_change > 10:
        report += f"- Founder consistently adds ~{avg_length_change}% more text. Generated copy may be too terse.\n"

    report += "\n---\nGenerated by monthly-learnings.py\n"

    # Write to memory
    os.makedirs(MEMORY_DIR, exist_ok=True)
    output_path = os.path.join(MEMORY_DIR, f"copy-learnings-{month}.md")
    with open(output_path, "w") as f:
        f.write(report)

    print(f"Report written to {output_path}")
    print(report)
    db.close()

if __name__ == "__main__":
    days = 30
    if len(sys.argv) > 1:
        try:
            days = int(sys.argv[1])
        except ValueError:
            pass
    analyze_edits(days)
