#!/usr/bin/env python3
"""Generate docs/reference/*.md, one catalog per surface class, from the code.

The catalogs are Layer 4 of the documentation: every script, tool, command, skill, hook,
job, rule, agent, style and CLI verb, with its path and its one-line purpose read from the
file itself. They are generated, never hand-edited: docs/check_coverage.py regenerates them
into a temp dir and diffs, so a catalog that drifts from the code is a red gate, not a
stale page. Usage: python3 docs/generate_reference.py [--out DIR]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import inventory  # noqa: E402

TITLES = {
    "script": ("scripts", "Every script", "Every executable script in the live tree (q-system/.q-system, q-system/hooks, scripts/, and the repo root), with the first line of its own docstring or header comment."),
    "test": ("tests", "Every test", "Every test file, so a reader can find the proof behind a script. A script with no test here has no proof beyond its own run."),
    "mcp_tool": ("mcp-tools", "Every MCP tool", "Every tool the kipi MCP server exposes to a Claude Code session, with the first line of its docstring. Tools marked RETIRED in their own docstring belong to the retired 9-phase morning pipeline."),
    "resource": ("mcp-resources", "Every MCP resource", "Every kipi:// resource URI the server serves."),
    "command": ("commands", "Every slash command", "Every slash command shipped by a plugin, with its frontmatter description."),
    "skill": ("skills", "Every skill", "Every skill shipped by a plugin, with its frontmatter description. A skill is a packaged instruction set the model loads when its trigger fires."),
    "hook": ("hooks", "Every hook", "Every hook script wired in .claude/settings.json, settings-template.json, or a plugin's hooks.json, with the event and matcher it fires on."),
    "job": ("jobs", "Every launchd job", "Every com.kipi.* launchd label found in the live tree."),
    "rule": ("rules", "Every rule", "Every always-on or path-scoped rule file under .claude/rules."),
    "agent": ("agents", "Every agent", "Every custom agent definition under .claude/agents, with its description."),
    "style": ("output-styles", "Every output style", "Every output style under .claude/output-styles."),
    "cli_verb": ("cli-verbs", "Every kipi CLI verb", "Every verb the kipi dispatcher accepts, read from its case statement."),
}


def render(cls: str, items: list[inventory.Surface]) -> str:
    slug, title, blurb = TITLES[cls]
    lines = [f"# {title}", "", f"<!-- GENERATED by docs/generate_reference.py from the code. Do not edit; docs/check_coverage.py diffs this against a fresh generation. -->", "", blurb, "", f"Count: {len(items)}", ""]
    if cls == "hook":
        lines.append("| Script | Fires on | Wired in |")
        lines.append("|---|---|---|")
        for s in sorted(items, key=lambda x: x.name):
            lines.append(f"| `{s.name}` | {s.doc} | `{s.path}` |")
    elif cls == "cli_verb":
        for s in items:
            lines.append(f"- `kipi {s.name}`")
    elif cls in ("resource", "job", "rule", "style"):
        for s in sorted(items, key=lambda x: x.name):
            lines.append(f"- `{s.name}`" + (f" ({s.path})" if s.path and cls != "rule" else ""))
    else:
        lines.append("| Name | Path | Purpose |")
        lines.append("|---|---|---|")
        for s in sorted(items, key=lambda x: (x.path, x.name)):
            doc = (s.doc or "").replace("|", "\\|")
            lines.append(f"| `{s.name}` | `{s.path}` | {doc} |")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(HERE / "reference"))
    args = ap.parse_args(argv)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    surfaces = inventory.enumerate_surfaces()
    by: dict[str, list[inventory.Surface]] = {}
    for s in surfaces:
        by.setdefault(s.cls, []).append(s)
    for cls in inventory.ORDER:
        slug = TITLES[cls][0]
        (out / f"{slug}.md").write_text(render(cls, by.get(cls, [])), encoding="utf-8")
    index = ["# Reference catalogs", "", "<!-- GENERATED by docs/generate_reference.py. -->", "",
             "Generated from the code. Each page lists every surface of one class; the coverage gate regenerates and diffs them.", ""]
    for cls in inventory.ORDER:
        slug, title, _ = TITLES[cls]
        index.append(f"- [{title}]({slug}.md) ({len(by.get(cls, []))})")
    index.append("")
    (out / "README.md").write_text("\n".join(index), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
